var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.arrayIteratorImpl=function(e){var f=0;return function(){return f<e.length?{done:!1,value:e[f++]}:{done:!0}}};$jscomp.arrayIterator=function(e){return{next:$jscomp.arrayIteratorImpl(e)}};$jscomp.makeIterator=function(e){var f="undefined"!=typeof Symbol&&Symbol.iterator&&e[Symbol.iterator];return f?f.call(e):$jscomp.arrayIterator(e)};
$jscomp.getGlobal=function(e){return"undefined"!=typeof window&&window===e?e:"undefined"!=typeof global&&null!=global?global:e};$jscomp.global=$jscomp.getGlobal(this);$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(e,f,l){e!=Array.prototype&&e!=Object.prototype&&(e[f]=l.value)};
$jscomp.polyfill=function(e,f,l,m){if(f){l=$jscomp.global;e=e.split(".");for(m=0;m<e.length-1;m++){var h=e[m];h in l||(l[h]={});l=l[h]}e=e[e.length-1];m=l[e];f=f(m);f!=m&&null!=f&&$jscomp.defineProperty(l,e,{configurable:!0,writable:!0,value:f})}};$jscomp.FORCE_POLYFILL_PROMISE=!1;
$jscomp.polyfill("Promise",function(e){function f(){this.batch_=null}function l(a){return a instanceof h?a:new h(function(b,d){b(a)})}if(e&&!$jscomp.FORCE_POLYFILL_PROMISE)return e;f.prototype.asyncExecute=function(a){null==this.batch_&&(this.batch_=[],this.asyncExecuteBatch_());this.batch_.push(a);return this};f.prototype.asyncExecuteBatch_=function(){var a=this;this.asyncExecuteFunction(function(){a.executeBatch_()})};var m=$jscomp.global.setTimeout;f.prototype.asyncExecuteFunction=function(a){m(a,
0)};f.prototype.executeBatch_=function(){for(;this.batch_&&this.batch_.length;){var a=this.batch_;this.batch_=[];for(var b=0;b<a.length;++b){var d=a[b];a[b]=null;try{d()}catch(c){this.asyncThrow_(c)}}}this.batch_=null};f.prototype.asyncThrow_=function(a){this.asyncExecuteFunction(function(){throw a;})};var h=function(a){this.state_=0;this.result_=void 0;this.onSettledCallbacks_=[];var b=this.createResolveAndReject_();try{a(b.resolve,b.reject)}catch(d){b.reject(d)}};h.prototype.createResolveAndReject_=
function(){function a(a){return function(c){d||(d=!0,a.call(b,c))}}var b=this,d=!1;return{resolve:a(this.resolveTo_),reject:a(this.reject_)}};h.prototype.resolveTo_=function(a){if(a===this)this.reject_(new TypeError("A Promise cannot resolve to itself"));else if(a instanceof h)this.settleSameAsPromise_(a);else{a:switch(typeof a){case "object":var b=null!=a;break a;case "function":b=!0;break a;default:b=!1}b?this.resolveToNonPromiseObj_(a):this.fulfill_(a)}};h.prototype.resolveToNonPromiseObj_=function(a){var b=
void 0;try{b=a.then}catch(d){this.reject_(d);return}"function"==typeof b?this.settleSameAsThenable_(b,a):this.fulfill_(a)};h.prototype.reject_=function(a){this.settle_(2,a)};h.prototype.fulfill_=function(a){this.settle_(1,a)};h.prototype.settle_=function(a,b){if(0!=this.state_)throw Error("Cannot settle("+a+", "+b+"): Promise already settled in state"+this.state_);this.state_=a;this.result_=b;this.executeOnSettledCallbacks_()};h.prototype.executeOnSettledCallbacks_=function(){if(null!=this.onSettledCallbacks_){for(var a=
0;a<this.onSettledCallbacks_.length;++a)p.asyncExecute(this.onSettledCallbacks_[a]);this.onSettledCallbacks_=null}};var p=new f;h.prototype.settleSameAsPromise_=function(a){var b=this.createResolveAndReject_();a.callWhenSettled_(b.resolve,b.reject)};h.prototype.settleSameAsThenable_=function(a,b){var d=this.createResolveAndReject_();try{a.call(b,d.resolve,d.reject)}catch(c){d.reject(c)}};h.prototype.then=function(a,b){function d(a,b){return"function"==typeof a?function(b){try{c(a(b))}catch(t){n(t)}}:
b}var c,n,e=new h(function(a,b){c=a;n=b});this.callWhenSettled_(d(a,c),d(b,n));return e};h.prototype.catch=function(a){return this.then(void 0,a)};h.prototype.callWhenSettled_=function(a,b){function d(){switch(c.state_){case 1:a(c.result_);break;case 2:b(c.result_);break;default:throw Error("Unexpected state: "+c.state_);}}var c=this;null==this.onSettledCallbacks_?p.asyncExecute(d):this.onSettledCallbacks_.push(d)};h.resolve=l;h.reject=function(a){return new h(function(b,d){d(a)})};h.race=function(a){return new h(function(b,
d){for(var c=$jscomp.makeIterator(a),n=c.next();!n.done;n=c.next())l(n.value).callWhenSettled_(b,d)})};h.all=function(a){var b=$jscomp.makeIterator(a),d=b.next();return d.done?l([]):new h(function(a,n){function c(b){return function(d){e[b]=d;f--;0==f&&a(e)}}var e=[],f=0;do e.push(void 0),f++,l(d.value).callWhenSettled_(c(e.length-1),n),d=b.next();while(!d.done)})};return h},"es6","es3");
$jscomp.checkStringArgs=function(e,f,l){if(null==e)throw new TypeError("The 'this' value for String.prototype."+l+" must not be null or undefined");if(f instanceof RegExp)throw new TypeError("First argument to String.prototype."+l+" must not be a regular expression");return e+""};
$jscomp.polyfill("String.prototype.repeat",function(e){return e?e:function(e){var f=$jscomp.checkStringArgs(this,null,"repeat");if(0>e||1342177279<e)throw new RangeError("Invalid count value");e|=0;for(var m="";e;)if(e&1&&(m+=f),e>>>=1)f+=f;return m}},"es6","es3");
function _typeof(e){_typeof="function"===typeof Symbol&&"symbol"===typeof Symbol.iterator?function(e){return typeof e}:function(e){return e&&"function"===typeof Symbol&&e.constructor===Symbol&&e!==Symbol.prototype?"symbol":typeof e};return _typeof(e)}window.seraph_pds||(window.seraph_pds={});
(function(){function e(a,b){var d=2<arguments.length&&void 0!==arguments[2]?arguments[2]:null,c=b.split(3<arguments.length&&void 0!==arguments[3]?arguments[3]:".").reduce(function(a,b){return"object"===_typeof(a)?a[b]:void 0},a);return void 0===c?d:c}function f(a,b,d){if("string"!==typeof a)return a;if(Array.isArray(b)){for(var c=0;c<b.length;c++)a=f(a,b[c],Array.isArray(d)?d[c]:d);return a}"string"!==typeof b&&(b=""+b);"string"!==typeof d&&(d=""+d);for(c=0;;){c=a.indexOf(b,c);if(-1==c)break;a=a.substr(0,
c)+d+a.substr(c+b.length);c+=d.length}return a}function l(a,b){var d=2<arguments.length&&void 0!==arguments[2]?arguments[2]:void 0;if("string"===typeof b)return a.indexOf(b,d);if(!Array.isArray(b))return-1;var c=-1;for(e in b){var e=b[e];var f=a.indexOf(e,d);-1!=f&&(-1==c||c>f)&&(c=f)}return c}function m(a,b){var d=2<arguments.length&&void 0!==arguments[2]?arguments[2]:void 0;if("string"===typeof b)return a.lastIndexOf(b,d);if(!Array.isArray(b))return-1;var c=-1;for(e in b){var e=b[e];var f=a.lastIndexOf(e,
d);-1!=f&&(-1==c||c<f)&&(c=f)}return c}function h(a){var b=1<arguments.length&&void 0!==arguments[1]?arguments[1]:!0;if(!a||"object"!==_typeof(a))return a;var d=Array===a.constructor?[]:{};for(var c in a)d[c]=b?h(a[c]):a[c];return d}function p(a,b){function d(f,n){var h=c[f];if(!h){var l=b[f];if(!l){h="function"==typeof require&&require;if(!n&&h)return h(f,!0);if(e)return e(f,!0);throw Error('Cannot find module "'+f+'"');}h=c[f]={exports:{}};l[0].call(h.exports,function(a){var b=l[1][a];return d(b?
b:a)},h,h.exports,p,a,b,c)}return h.exports}for(var c=2<arguments.length&&void 0!==arguments[2]?arguments[2]:{},e="function"==typeof require&&require,f=0;f<a.length;f++)d(a[f]);return d}seraph_pds.Gen={DoesFuncExist:function(a){return"function"===typeof e(window,a)},ParseCmdline:function(a){var b=1<arguments.length&&void 0!==arguments[1]?arguments[1]:!0,d=[];if("string"!=typeof a)return d;a=a.trim();for(var c=a.length,e=!1,f="",h=0;h<c;h++)" "!==a.charAt(h)||e?'"'===a.charAt(h)&&b?e=!e:f+=a.charAt(h):
(d.push(f),f="");d.push(f);return d},GetFileName:function(a){var b=1<arguments.length&&void 0!==arguments[1]?arguments[1]:!1;a=a.split("\\").pop().split("/").pop();b&&(b=a.lastIndexOf("."),-1!=b&&(a=a.substr(0,b)));return a},GetFileDir:function(a){var b=1<arguments.length&&void 0!==arguments[1]?arguments[1]:!1,d=2<arguments.length&&void 0!==arguments[2]?arguments[2]:1;if(!d)return a;if(0<d)for(;;){var c=m(a,["/","\\"],c);if(-1==c||0==c)break;d--;if(!d)break;c--}else for(d*=-1;;){c=l(a,["/","\\"],
c);if(-1==c)break;d--;if(!d)break;c++}return-1==c?"":a.substr(0,c+(b?1:0))},GetFileExt:function(a){var b=1<arguments.length&&void 0!==arguments[1]?arguments[1]:!1,d=a.lastIndexOf(".");return-1==d?"":a.substr(d+(b?0:1))},CheckLastSlash:function(a){"string"!=typeof a&&(a="");return"/"==a.substr(-1)},SetLastSlash:function(a){var b=1<arguments.length&&void 0!==arguments[1]?arguments[1]:!0,d=2<arguments.length&&void 0!==arguments[2]?arguments[2]:"/";if("string"!==typeof a||!a.length)return"";if(a.lastIndexOf(d)==
a.length-1){if(!b)return a.substr(0,a.length-1)}else if(b)return a+d;return a},SetFirstSlash:function(a){var b=1<arguments.length&&void 0!==arguments[1]?arguments[1]:!0,d=2<arguments.length&&void 0!==arguments[2]?arguments[2]:"/";if("string"!==typeof a||!a.length)return"";if(0==a.indexOf(d)){if(!b)return a.substr(1)}else if(b)return d+a;return a},StrReplaceAll:f,StrIndexOf:l,StrLastIndexOf:m,FilterObjectKeys:function(a){var b=1<arguments.length&&void 0!==arguments[1]?arguments[1]:null,d=2<arguments.length&&
void 0!==arguments[2]?arguments[2]:null,c={},e;for(e in a)d&&-1!==d.indexOf(e)||b&&-1===b.indexOf(e)||(c[e]=a[e]);return c},DeepCopy:h,Extend:function(a,b,d){if(void 0===b)return a;for(var c in b){var e=b[c];d&&void 0===e||(a||(a={}),a[c]=e)}return a},JsonParse:function(a){try{var b=JSON.parse(a)}catch(d){}return b},GetObjField:e,SetObjField:function(a,b,d){var c=b.split(3<arguments.length&&void 0!==arguments[3]?arguments[3]:".");if(c.length){for(var e=0;e<c.length-1;e++){var f=c[e];a[f]||(a[f]=[]);
a=a[f]}f=c[c.length-1];"+"==f?a.push(d):a[f]=d}},AsyncChain:function(){return new Promise(function(a,b){a()})},RunModules:p,hr:{SEVERITY_SUCCESS:0,SEVERITY_ERROR:1,FACILITY_INTERNET:12,FACILITY_HTTP:25,S_OK:0,S_FALSE:1,E_NOTIMPL:2147500033,E_FAIL:2147500037,E_UNSUPPORTED:2147500065,E_INVALIDARG:2147942487,E_INVALID_STATE:2147947423,E_INTERNAL:2147943759,E_DATACORRUPTED:2147943792,E_NOT_FOUND:2147943568,E_ACCESS_DENIED:2147942405,E_ABORTED:2147943623,Make:function(a,b,d){return a<<31|b<<16|d&65535},
Code:function(a){return a&65535},Facility:function(a){return a>>16&8191},Succ:function(a){return!(a&2147483648)},Fail:function(a){return!!(a&2147483648)}}};seraph_pds.Plugin={GetErrorDescr:function(a){var b=1<arguments.length&&void 0!==arguments[1]?arguments[1]:null,d=2<arguments.length&&void 0!==arguments[2]?arguments[2]:!1,c=seraph_pds.Wp.Loc.GetApi(),e=c._x;c=c.sprintf;var f=c("0x%08X",a),h=d&&seraph_pds.Gen.hr.Succ(a)?c("0x%08X",seraph_pds.Gen.hr.Make(seraph_pds.Gen.hr.SEVERITY_ERROR,seraph_pds.Gen.hr.Facility(a),
a)):null;d=[];b&&(d.push({id:f,ctx:b}),h&&d.push({id:h,ctx:b}));d.push({id:f,ctx:"admin.ErrDescr_Common"});h&&d.push({id:h,ctx:"admin.ErrDescr_Common"});d.push({id:"Def_%08X",ctx:"admin.ErrDescr_Common"});for(var l in d)if(h=d[l],b=h.id,h=c(e(b,h.ctx,"seraphinite-post-docx-source"),a),h!=b)return h;return f},GetRootUrl:function(){return this._int.urlRoot},_int:{urlRoot:""}};seraph_pds.Wp={Loc:{GetApi:function(){var a=null;a=window.wp&&window.wp.i18n?window.wp.i18n:{__:function(a,d){return seraph_pds.Wp.Loc._int.dcnpgettext(d,
void 0,a)},_x:function(a,d,c){return seraph_pds.Wp.Loc._int.dcnpgettext(c,d,a)},_n:function(a,d,c,e){return seraph_pds.Wp.Loc._int.dcnpgettext(e,void 0,a,d,c)},_nx:function(a,d,c,e,f){return seraph_pds.Wp.Loc._int.dcnpgettext(f,e,a,d,c)},sprintf:seraph_pds.Wp.Loc._int.sprintf};a.vsprintf||(a.vsprintf=function(b,d){return a.sprintf.apply(null,[b].concat(d||[]))});return a},SetData:function(a,b){return window.wp&&window.wp.i18n?window.wp.i18n.setLocaleData(a,b):seraph_pds.Wp.Loc._int.setLocaleData(a,
b)},GetLang:function(){return seraph_pds.Wp.Loc._int.lang}}};(function(){function a(a){for(var b=[],d=[],e,c,g;e=a.match(p);){c=e[0];for((g=a.substr(0,e.index).trim())&&b.push(g);g=d.pop();){if(m[c]){if(m[c][0]===g){c=m[c][1]||c;break}}else if(0<=l.indexOf(g)||h[g]<h[c]){d.push(g);break}b.push(g)}m[c]||d.push(c);a=a.substr(e.index+c.length)}(a=a.trim())&&b.push(a);return b.concat(d.reverse())}function b(b){var d=a(b);return function(a){a:{var b=[],e,c;for(e=0;e<d.length;e++){var f=d[e];if(c=t[f])try{var h=
c.apply(null,b.splice(-1*c.length))}catch(k){a=k;break a}else h=a.hasOwnProperty(f)?a[f]:+f;b.push(h)}a=b[0]}return a}}function d(a){var d=b(a);return function(a){return+d({n:a})}}function e(a){var b=a;if(u[b])b=u[b];else{for(var d=b,c,f=[],g=0;d;){if(null!==(c=q.text.exec(d)))f.push(c[0]);else if(null!==(c=q.modulo.exec(d)))f.push("%");else if(null!==(c=q.placeholder.exec(d))){if(c[2]){g|=1;var h=[],r=c[2],k;if(null!==(k=q.key.exec(r)))for(h.push(k[1]);""!==(r=r.substring(k[0].length));)if(null!==
(k=q.key_access.exec(r)))h.push(k[1]);else if(null!==(k=q.index_access.exec(r)))h.push(k[1]);else throw new SyntaxError("[sprintf] failed to parse named argument key");else throw new SyntaxError("[sprintf] failed to parse named argument key");c[2]=h}else g|=2;if(3===g)throw Error("[sprintf] mixing positional and named placeholders is not (yet) supported");f.push({placeholder:c[0],param_no:c[1],keys:c[2],sign:c[3],pad_char:c[4],align:c[5],width:c[6],precision:c[7],type:c[8]})}else throw new SyntaxError("[sprintf] unexpected placeholder");
d=d.substring(c[0].length)}b=u[b]=f}d=arguments;c=1;f=b.length;h="";var l,m;for(r=0;r<f;r++)if("string"===typeof b[r])h+=b[r];else if("object"===_typeof(b[r])){k=b[r];if(k.keys)for(g=d[c],l=0;l<k.keys.length;l++){if(void 0==g)throw Error(e('[sprintf] Cannot access property "%s" of undefined value "%s"',k.keys[l],k.keys[l-1]));g=g[k.keys[l]]}else g=k.param_no?d[k.param_no]:d[c++];q.not_type.test(k.type)&&q.not_primitive.test(k.type)&&g instanceof Function&&(g=g());if(q.numeric_arg.test(k.type)&&"number"!==
typeof g&&isNaN(g))throw new TypeError(e("[sprintf] expecting number but found %T",g));q.number.test(k.type)&&(m=0<=g);switch(k.type){case "b":g=parseInt(g,10).toString(2);break;case "c":g=String.fromCharCode(parseInt(g,10));break;case "d":case "i":g=parseInt(g,10);break;case "j":g=JSON.stringify(g,null,k.width?parseInt(k.width):0);break;case "e":g=k.precision?parseFloat(g).toExponential(k.precision):parseFloat(g).toExponential();break;case "f":g=k.precision?parseFloat(g).toFixed(k.precision):parseFloat(g);
break;case "g":g=k.precision?String(Number(g.toPrecision(k.precision))):parseFloat(g);break;case "o":g=(parseInt(g,10)>>>0).toString(8);break;case "s":g=String(g);g=k.precision?g.substring(0,k.precision):g;break;case "t":g=String(!!g);g=k.precision?g.substring(0,k.precision):g;break;case "T":g=Object.prototype.toString.call(g).slice(8,-1).toLowerCase();g=k.precision?g.substring(0,k.precision):g;break;case "u":g=parseInt(g,10)>>>0;break;case "v":g=g.valueOf();g=k.precision?g.substring(0,k.precision):
g;break;case "x":g=(parseInt(g,10)>>>0).toString(16);break;case "X":g=(parseInt(g,10)>>>0).toString(16).toUpperCase()}if(q.json.test(k.type))h+=g;else{if(!q.number.test(k.type)||m&&!k.sign)var n="";else n=m?"+":"-",g=g.toString().replace(q.sign,"");l=k.pad_char?"0"===k.pad_char?"0":k.pad_char.charAt(1):" ";var p=k.width-(n+g).length;p=k.width?0<p?l.repeat(p):"":"";h+=k.align?n+g+p:"0"===l?n+p+g:p+n+g}}return h}seraph_pds.Wp.Loc._int={data:{},pluralForms:{},options:{contextDelimiter:"\u0004"},lang:"",
setLocaleData:function(a,b){a||(a=f);var d=this.data[b];if(d)for(var c in d)a[c]=d[c];this.data[b]=a},dcnpgettext:function(a,b,d,c,e){this.data[a]||this.setLocaleData(void 0,a);e=void 0===e?0:this.getPluralForm(a,e);var f=d;b&&(f=b+this.options.contextDelimiter+d);return(a=this.data[a][f])&&a[e]?a[e]:0===e?d:c},getPluralForm:function(a,b){var c=this.pluralForms[a];if(!c){c=this.data[a][""];a:{var e;c=(c["Plural-Forms"]||c["plural-forms"]||c.plural_forms).split(";");for(e=0;e<c.length;e++){var f=c[e].trim();
if(0===f.indexOf("plural=")){c=f.substr(7);break a}}c=void 0}c=this.pluralForms[a]=d(c)}return c(b)},sprintf:e};var f={"":{plural_forms:"plural=(n!=1)"}};var h={"(":9,"!":8,"*":7,"/":7,"%":7,"+":6,"-":6,"<":5,"<=":5,">":5,">=":5,"==":4,"!=":4,"&&":3,"||":2,"?":1,"?:":1};var l=["(","?"];var m={")":["("],":":["?","?:"]};var p=/<=|>=|==|!=|&&|\|\||\?:|\(|!|\*|\/|%|\+|-|<|>|\?|\)|:/;var t={"!":function(a){return!a},"*":function(a,b){return a*b},"/":function(a,b){return a/b},"%":function(a,b){return a%
b},"+":function(a,b){return a+b},"-":function(a,b){return a-b},"<":function(a,b){return a<b},"<=":function(a,b){return a<=b},">":function(a,b){return a>b},">=":function(a,b){return a>=b},"==":function(a,b){return a===b},"!=":function(a,b){return a!==b},"&&":function(a,b){return a&&b},"||":function(a,b){return a||b},"?:":function(a,b,c){if(a)throw b;return c}},q={not_string:/[^s]/,not_bool:/[^t]/,not_type:/[^T]/,not_primitive:/[^v]/,number:/[diefg]/,numeric_arg:/[bcdiefguxX]/,json:/[j]/,not_json:/[^j]/,
text:/^[^\x25]+/,modulo:/^\x25{2}/,placeholder:/^\x25(?:([1-9]\d*)\$|\(([^)]+)\))?(\+)?(0|'[^$])?(-)?(\d+)?(?:\.(\d+))?([b-gijostTuvxX])/,key:/^([a-z_][a-z_\d]*)/i,key_access:/^\.([a-z_][a-z_\d]*)/i,index_access:/^\[(\d+)\]/,sign:/^[+-]/},u=Object.create(null)})()})();
