var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.findInternal=function(a,c,d){a instanceof String&&(a=String(a));for(var h=a.length,f=0;f<h;f++){var n=a[f];if(c.call(d,n,f,a))return{i:f,v:n}}return{i:-1,v:void 0}};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,c,d){a!=Array.prototype&&a!=Object.prototype&&(a[c]=d.value)};
$jscomp.getGlobal=function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global&&null!=global?global:a};$jscomp.global=$jscomp.getGlobal(this);$jscomp.polyfill=function(a,c,d,h){if(c){d=$jscomp.global;a=a.split(".");for(h=0;h<a.length-1;h++){var f=a[h];f in d||(d[f]={});d=d[f]}a=a[a.length-1];h=d[a];c=c(h);c!=h&&null!=c&&$jscomp.defineProperty(d,a,{configurable:!0,writable:!0,value:c})}};
$jscomp.polyfill("Array.prototype.find",function(a){return a?a:function(a,d){return $jscomp.findInternal(this,a,d).v}},"es6","es3");$jscomp.arrayIteratorImpl=function(a){var c=0;return function(){return c<a.length?{done:!1,value:a[c++]}:{done:!0}}};$jscomp.arrayIterator=function(a){return{next:$jscomp.arrayIteratorImpl(a)}};$jscomp.makeIterator=function(a){var c="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];return c?c.call(a):$jscomp.arrayIterator(a)};
$jscomp.FORCE_POLYFILL_PROMISE=!1;
$jscomp.polyfill("Promise",function(a){function c(){this.batch_=null}function d(a){return a instanceof f?a:new f(function(p,c){p(a)})}if(a&&!$jscomp.FORCE_POLYFILL_PROMISE)return a;c.prototype.asyncExecute=function(a){null==this.batch_&&(this.batch_=[],this.asyncExecuteBatch_());this.batch_.push(a);return this};c.prototype.asyncExecuteBatch_=function(){var a=this;this.asyncExecuteFunction(function(){a.executeBatch_()})};var h=$jscomp.global.setTimeout;c.prototype.asyncExecuteFunction=function(a){h(a,
0)};c.prototype.executeBatch_=function(){for(;this.batch_&&this.batch_.length;){var a=this.batch_;this.batch_=[];for(var c=0;c<a.length;++c){var d=a[c];a[c]=null;try{d()}catch(l){this.asyncThrow_(l)}}}this.batch_=null};c.prototype.asyncThrow_=function(a){this.asyncExecuteFunction(function(){throw a;})};var f=function(a){this.state_=0;this.result_=void 0;this.onSettledCallbacks_=[];var c=this.createResolveAndReject_();try{a(c.resolve,c.reject)}catch(r){c.reject(r)}};f.prototype.createResolveAndReject_=
function(){function a(a){return function(p){d||(d=!0,a.call(c,p))}}var c=this,d=!1;return{resolve:a(this.resolveTo_),reject:a(this.reject_)}};f.prototype.resolveTo_=function(a){if(a===this)this.reject_(new TypeError("A Promise cannot resolve to itself"));else if(a instanceof f)this.settleSameAsPromise_(a);else{a:switch(typeof a){case "object":var c=null!=a;break a;case "function":c=!0;break a;default:c=!1}c?this.resolveToNonPromiseObj_(a):this.fulfill_(a)}};f.prototype.resolveToNonPromiseObj_=function(a){var c=
void 0;try{c=a.then}catch(r){this.reject_(r);return}"function"==typeof c?this.settleSameAsThenable_(c,a):this.fulfill_(a)};f.prototype.reject_=function(a){this.settle_(2,a)};f.prototype.fulfill_=function(a){this.settle_(1,a)};f.prototype.settle_=function(a,c){if(0!=this.state_)throw Error("Cannot settle("+a+", "+c+"): Promise already settled in state"+this.state_);this.state_=a;this.result_=c;this.executeOnSettledCallbacks_()};f.prototype.executeOnSettledCallbacks_=function(){if(null!=this.onSettledCallbacks_){for(var a=
0;a<this.onSettledCallbacks_.length;++a)n.asyncExecute(this.onSettledCallbacks_[a]);this.onSettledCallbacks_=null}};var n=new c;f.prototype.settleSameAsPromise_=function(a){var c=this.createResolveAndReject_();a.callWhenSettled_(c.resolve,c.reject)};f.prototype.settleSameAsThenable_=function(a,c){var d=this.createResolveAndReject_();try{a.call(c,d.resolve,d.reject)}catch(l){d.reject(l)}};f.prototype.then=function(a,c){function d(a,c){return"function"==typeof a?function(c){try{l(a(c))}catch(b){h(b)}}:
c}var l,h,p=new f(function(a,c){l=a;h=c});this.callWhenSettled_(d(a,l),d(c,h));return p};f.prototype.catch=function(a){return this.then(void 0,a)};f.prototype.callWhenSettled_=function(a,c){function d(){switch(f.state_){case 1:a(f.result_);break;case 2:c(f.result_);break;default:throw Error("Unexpected state: "+f.state_);}}var f=this;null==this.onSettledCallbacks_?n.asyncExecute(d):this.onSettledCallbacks_.push(d)};f.resolve=d;f.reject=function(a){return new f(function(c,d){d(a)})};f.race=function(a){return new f(function(c,
f){for(var l=$jscomp.makeIterator(a),h=l.next();!h.done;h=l.next())d(h.value).callWhenSettled_(c,f)})};f.all=function(a){var c=$jscomp.makeIterator(a),h=c.next();return h.done?d([]):new f(function(a,f){function l(c){return function(b){n[c]=b;p--;0==p&&a(n)}}var n=[],p=0;do n.push(void 0),p++,d(h.value).callWhenSettled_(l(n.length-1),f),h=c.next();while(!h.done)})};return f},"es6","es3");
$jscomp.polyfill("Promise.prototype.finally",function(a){return a?a:function(a){return this.then(function(c){return Promise.resolve(a()).then(function(){return c})},function(c){return Promise.resolve(a()).then(function(){throw c;})})}},"es9","es3");$jscomp.polyfill("Object.is",function(a){return a?a:function(a,d){return a===d?0!==a||1/a===1/d:a!==a&&d!==d}},"es6","es3");
$jscomp.polyfill("Array.prototype.includes",function(a){return a?a:function(a,d){var c=this;c instanceof String&&(c=String(c));var f=c.length;d=d||0;for(0>d&&(d=Math.max(d+f,0));d<f;d++){var n=c[d];if(n===a||Object.is(n,a))return!0}return!1}},"es7","es3");
$jscomp.checkStringArgs=function(a,c,d){if(null==a)throw new TypeError("The 'this' value for String.prototype."+d+" must not be null or undefined");if(c instanceof RegExp)throw new TypeError("First argument to String.prototype."+d+" must not be a regular expression");return a+""};$jscomp.polyfill("String.prototype.includes",function(a){return a?a:function(a,d){return-1!==$jscomp.checkStringArgs(this,a,"includes").indexOf(a,d||0)}},"es6","es3");
function _typeof(a){_typeof="function"===typeof Symbol&&"symbol"===typeof Symbol.iterator?function(a){return typeof a}:function(a){return a&&"function"===typeof Symbol&&a.constructor===Symbol&&a!==Symbol.prototype?"symbol":typeof a};return _typeof(a)}window.seraph_pds||(window.seraph_pds={});
(function(){function a(b){var a=1<arguments.length&&void 0!==arguments[1]?arguments[1]:null,e=2<arguments.length&&void 0!==arguments[2]?arguments[2]:null,q=3<arguments.length&&void 0!==arguments[3]?arguments[3]:!1,m=4<arguments.length&&void 0!==arguments[4]?arguments[4]:null;null===a&&(a="");null===m&&(m={});if(m.noTagsIfNoContent&&!a)return a;e=c(b,e,q);if(q)return e;l(a)?a[0]=e+a[0]:a=e+a;e=d(b);l(a)?a[a.length-1]+=e:a+=e;return a}function c(b){var a=2<arguments.length&&void 0!==arguments[2]?arguments[2]:
!1;if(!b)return"";var e=1<arguments.length&&void 0!==arguments[1]?arguments[1]:null,q="";if(l(e))for(var c in e){var g=e[c];if(void 0!==g){if("style"==c)(g=l(g)?r(g):t(g,!1,'"'))||(g=void 0);else if(l(g)){for(var d="",f=!0,h=0;h<g.length;h++)f||(d+=" "),d+=g[h],f=!1;g=d}else g=t(g,!1,'"');void 0!==g&&(q+=" "+c+'="'+g+'"')}}else"string"===typeof e&&(q+=" "+e);return"<"+b+q+(a?" /":"")+">"}function d(b){return b?"</"+b+">":""}function h(b,a){var k=2<arguments.length&&void 0!==arguments[2]?arguments[2]:
!1,q=3<arguments.length&&void 0!==arguments[3]?arguments[3]:!1,c=4<arguments.length&&void 0!==arguments[4]?arguments[4]:null,g=5<arguments.length&&void 0!==arguments[5]?arguments[5]:null,d=6<arguments.length&&void 0!==arguments[6]?arguments[6]:null;l(d)||(d={});a&&(d.id=a);return f("checkbox",b,d,null,k,q,c,g)}function f(b,k,e){var q=3<arguments.length&&void 0!==arguments[3]?arguments[3]:null,m=4<arguments.length&&void 0!==arguments[4]?arguments[4]:!1,g=5<arguments.length&&void 0!==arguments[5]?arguments[5]:
!1,f=6<arguments.length&&void 0!==arguments[6]?arguments[6]:null,h=7<arguments.length&&void 0!==arguments[7]?arguments[7]:null,n="";l(e)||(e={});h&&(l(f)||(f={}),e.title=f.title=h);h="";if(l(k)){var p=k;k="";for(var r in p)if(l(r)){p="";var t=null;isset(r[2])&&(t=r[2]);var v=r[0];k+='<a href="#" id="'+v+'_view" onclick="var ctl = document.getElementById( \''+v+"' ); var iNew = ctl.selectedIndex + 1; if( iNew >= ctl.options.length ) iNew = 0; if( ctl.selectedIndex != iNew ) { ctl.selectedIndex = iNew; ctl.onchange(); } return false;\">";
for(var u in r[1])isset(u[2])&&u[2]&&(t=u[0]),p+='<option value="'+u[0]+'"',t==u[0]&&(k+=u[1],p+=" selected"),p+=">"+u[1]+"</option>";k+="</a>";h+='<select id="'+v+'"'+(g?' name="'+v+'"':"")+' style="display: none;"';h+=" onchange=\"var text = this.selectedIndex >= 0 ? this.options[ this.selectedIndex ].text : ''; document.getElementById( '"+v+"_view' ).text = text;\">";h+=p;h+="</select>"}else k+=r}n+=c("label",f);f=e.id;e.type=b;g&&f&&(e.name=f);q&&(e.value=q);m&&(e.checked="checked");n+=a("input",
null,e,!0);return n+=k+h+d("label")}function n(b){var a=2<arguments.length&&void 0!==arguments[2]?arguments[2]:!1;if(!b||!b.length)return"";var e=""+c("ul",1<arguments.length&&void 0!==arguments[1]?arguments[1]:null);for(var q=0;q<b.length;q++){var m=b[q];e+=c("li");e+=h(m.name,m.id,!1,a,null,null,{onchange:"seraph_pds.Ui._cb.CheckBoxTree_OnChange(this)"});m.items&&(e+=n(m.items,null,a));e+=d("li")}return e+=d("ul")}function p(b){b=jQuery("#seraph_pds_popup_"+b);1==b.attr("attr-modal")&&jQuery(".seraph_pds.popup_modal_overlay").hide();
b.hide()}function t(b){var a=1<arguments.length&&void 0!==arguments[1]?arguments[1]:!1,e=2<arguments.length&&void 0!==arguments[2]?arguments[2]:null;if("string"!==typeof b)return b;b=seraph_pds.Gen.StrReplaceAll(b,"&","&amp;");'"'===e&&(b=seraph_pds.Gen.StrReplaceAll(b,'"',"&quot;"));"'"===e&&(b=seraph_pds.Gen.StrReplaceAll(b,"'","&#039;"));b=seraph_pds.Gen.StrReplaceAll(b,"<","&lt;");b=seraph_pds.Gen.StrReplaceAll(b,">","&gt;");a&&(b=seraph_pds.Gen.StrReplaceAll(b," ","&nbsp;"));return b}function r(b){var a=
"",e;for(e in b){var q=b[e];void 0!==q&&null!==q&&(a+=e+":"+q+";")}return a}function l(b){return b&&"object"===_typeof(b)}function w(b,a,e){var k=!1;void 0===a?(a=b.height(),b.css("opacity",0),b.css("height","0px")):k=!0;setTimeout(function(){k||b.addClass("smoothop");b.css("height",""+a+"px");setTimeout(function(){b.css("height","");b.css("opacity","");setTimeout(function(){b.removeClass("smoothop");e&&e(b)},200)},300)},k?50:0)}function A(b,a){var e=b.height();b.addClass("smoothop");b.css("opacity",
0);setTimeout(function(){b.css("height",""+e+"px");setTimeout(function(){b.css("height","0px");setTimeout(function(){a&&a(b,e)},300)},50)},200)}function x(b,a){var e=!a.children().length;b.find(".items-list-empty-content").first().toggle(e);a.toggle(!e)}function y(b,a,e){e||(e=a);jQuery(b).append(seraph_pds.Ui.Tag("span",seraph_pds.Ui.Tag("a","",{href:"","class":"dashicons dashicons-dismiss",onclick:"seraph_pds.Ui._cb.TokensList_DelItem(this);return false;"})+seraph_pds.Ui.Tag("span",e),{"data-id":a}))}
function z(b,a,e){var k=jQuery(b).find('input[type="hidden"]');if(a){a=seraph_pds.Gen.JsonParse(decodeURIComponent(k.val()))||[];for(var c in a)k=a[c],y(b,k,e?e(k):void 0)}else b.innerHTML=k[0].outerHTML}seraph_pds.Ui={EscHtml:t,HtmlToPlainText:function(b){var a=document.createElement("div");a.innerHTML=b;return a.textContent||a.innerText||""},Text:function(b){var a=1<arguments.length&&void 0!==arguments[1]?arguments[1]:0,e=2<arguments.length&&void 0!==arguments[2]?arguments[2]:!1,c=3<arguments.length&&
void 0!==arguments[3]?arguments[3]:!1;if("string"!==typeof b)return"";b=seraph_pds.Gen.StrReplaceAll(b,"&","&amp;");e&&(b=seraph_pds.Gen.StrReplaceAll(b,'"',"&quot;"),b=seraph_pds.Gen.StrReplaceAll(b,"'","&#39;"));b=seraph_pds.Gen.StrReplaceAll(b,"<","&lt;");b=seraph_pds.Gen.StrReplaceAll(b,">","&gt;");a&&(b=seraph_pds.Gen.StrReplaceAll(b," ","string"===typeof a?a:1==a?"&nbsp;":"&#32;"));if(c)for(a=0,e=b.length;a<e;a++)c=b.charCodeAt(a),255>=c||(b=b.substr(0,a)+"&#"+c+";"+b.substr(a+1),a+=b.length-
e,e=b.length);return b},Comment:function(b){"string"!==typeof b&&(b="");return"\x3c!-- "+b+" --\x3e"},Tag:a,TagOpen:c,TagClose:d,GetTagStyleAttrs:r,ParseTagStyleAttrs:function(b){"string"!==typeof b&&(b="");var a={};b=b.split(";");for(var e in b){var c=b[e],m=c.indexOf(":");if(-1!==m){var g=c.substr(0,m).trim();c=c.substr(m+1).trim();a[g]=c}}return a},Link:function(b,a){var e=2<arguments.length&&void 0!==arguments[2]?arguments[2]:!1,k=3<arguments.length&&void 0!==arguments[3]?arguments[3]:null,m=
4<arguments.length&&void 0!==arguments[4]?arguments[4]:null;null===m&&(m={});null===k&&(k={});if(a){var g="",f=k.linkPreContent;f&&(g+=f);m.href=a;e&&0!==a.indexOf("mailto:")&&(m.target="_blank");g+=c("a",m);l(b)?b[0]=g+b[0]:b=g+b}else if(k.noTextIfNoHref){if(!l(b))return"";b[0]="";b[b.length-1]="";3==b.length&&(b[1]="");return b}a&&(g=d("a"),(e=k.linkAfterContent)&&(g+=e),l(b)?b[b.length-1]+=g:b+=g);return b},Button:function(b){var c=1<arguments.length&&void 0!==arguments[1]?arguments[1]:!1,e=2<
arguments.length&&void 0!==arguments[2]?arguments[2]:null,d=3<arguments.length&&void 0!==arguments[3]?arguments[3]:null,m=4<arguments.length&&void 0!==arguments[4]?arguments[4]:"submit",g=5<arguments.length&&void 0!==arguments[5]?arguments[5]:null,f="button"==m&&-1!==b.indexOf("<");g||(g={});e&&(g.name=e);f||(g.type=m,g.value=b,b=null);Array.isArray(g.class)||(g.class=[]);g.class.push("button");c&&g.class.push("button-primary");d&&(Array.isArray(d)?g.class=g.class.concat(d):g.class.push(d));return a(f?
"button":"input",b,g)},CheckBox:h,RadioBox:function(a,c,e){var b=3<arguments.length&&void 0!==arguments[3]?arguments[3]:!1,k=4<arguments.length&&void 0!==arguments[4]?arguments[4]:null,d=5<arguments.length&&void 0!==arguments[5]?arguments[5]:null,h=6<arguments.length&&void 0!==arguments[6]?arguments[6]:null;l(h)||(h={});c&&(h.name=c);return f("radio",a,h,e,b,k,d)},CheckBoxTree:function(a){var b=1<arguments.length&&void 0!==arguments[1]?arguments[1]:null,e=2<arguments.length&&void 0!==arguments[2]?
arguments[2]:!1;l(b)||(b={});b.class=["seraph_pds_CheckBoxTree"];return n(a,b,e)},ComboShowDependedItems:function(a,c){function b(a){var b=jQuery(a).data("ns");b||(b=a.value);return b}for(var k=0<=a.selectedIndex?b(a.options[a.selectedIndex]):"",d=[],g=0;g<a.options.length;g++)d[b(a.options[g])]=!0;a=jQuery(c?c:a.parentNode);for(var f in d)f!=k&&a.find(".ns-"+f).each(function(){var a=jQuery(this),b=a.attr("name");b&&(a.attr("name-i",b),a.removeAttr("name"));a.hide()});a.find(".ns-"+k).each(function(){var a=
jQuery(this),b=a.attr("name-i");b&&(a.attr("name",b),a.removeAttr("name-i"));a.show()})},Spinner:function(b,c){c||(c={});seraph_pds.Gen.SetObjField(c,"class.+","seraph_pds_spinner"+(b?" big":""));return a("span",null,c)},LogItem:function(b,c){var e=2<arguments.length&&void 0!==arguments[2]?arguments[2]:!0;if("string"===typeof c){var k="dashicons-info",d="clrWpNone";switch(b){case "info":k="dashicons-info";d="clrWpInfo";break;case "success":k="dashicons-info";d="clrWpSucc";break;case "warning":k="dashicons-warning";
d="clrWpWarn";break;case "error":k="dashicons-warning",d="clrWpErr"}e&&(e=c.slice(-1),"."!=e&&"?"!=e&&(c+="."));return a("div",a("div",null,{"class":"icon dashicons "+k+" "+d})+a("div",c,{"class":"text"}),{"class":"logItem"})}},Apply:function(a){var b=!0;jQuery(a).find("[data-onapply]").each(function(){!1===seraph_pds.Gen.GetObjField(window,jQuery(this).data("onapply"))(this)&&(b=!1)});return b},PopupShow:function(a){var b=jQuery("#seraph_pds_popup_"+a),c=1==b.attr("attr-modal"),d=b.attr("attr-body");
d&&(b.removeAttr("attr-body"),b.html(decodeURIComponent(d)));c&&(jQuery(".seraph_pds.popup_modal_overlay").show(),jQuery(document).bind("keyup",function(b){if("Escape"===b.key)return p(a),!1}));b.show()},PopupClose:p,ScriptLoad:function(a,c){var b=2<arguments.length&&void 0!==arguments[2]?arguments[2]:null,d=3<arguments.length&&void 0!==arguments[3]?arguments[3]:!0;if(a)return new Promise(function(e,k){var f=b?a.getElementById(b):null;f?!0===d?e(!1):(a.head.removeChild(f),e(!0)):!0!==d?e(!1):(f=a.createElement("script"),
f.type="text/javascript",f.src=c,b&&(f.id=b),f.onload=function(){e(!0)},f.onerror=function(a){(a=seraph_pds.Gen.GetObjField(a,"target.src"))||(a=c);k("Can't load script: "+a)},a.head.appendChild(f))})},TokensList:{GetVal:function(a){a=jQuery(a).find('input[type="hidden"]');(a=seraph_pds.Gen.JsonParse(decodeURIComponent(a.val())))||(a=[]);return a},AddItem:function(a,c,e){var b=jQuery(a).find('input[type="hidden"]'),d=seraph_pds.Gen.JsonParse(decodeURIComponent(b.val()));d||(d=[]);d.includes(c)||(d.push(c),
b.val(encodeURIComponent(JSON.stringify(d))),y(a,c,e))},DelAllItems:function(a){a.innerHTML=jQuery(a).find('input[type="hidden"]')[0].outerHTML;jQuery(a).find('input[type="hidden"]').val(encodeURIComponent(JSON.stringify([])))},InitItems:z,AreItemsInited:function(a){return a.children&&1<a.children.length},ShowProgress:function(a,c){c?jQuery(a).append(seraph_pds.Ui.Spinner(!0)):z(a,!1)}},ItemsList:{_Init:function(a,c,e,d,f,g){a=jQuery(a).find("ul.items-list").first();a.length&&(a[0]._ItemsListCtx=
{level:g,onItemDel:c,nextItemId:e,contentNewItem:seraph_pds.Gen.StrReplaceAll(d,"scrapt>","script>")},f&&(a.sortable({placeholder:"ui-sortable-placeholder",forcePlaceholderSize:!0}),a.disableSelection(),a.sortable("option","cancel",a.sortable("option","cancel")+",.rs")))},AddItem:function(a,c){a=jQuery(a);c=a.find("ul.items-list").first();if(c.length){var b=c[0]._ItemsListCtx;c.append(seraph_pds.Gen.StrReplaceAll(b.contentNewItem,"{{"+b.level+"itemId}}",b.nextItemId));b.nextItemId++;a.find(".items-list-empty-content").first().hide();
c.show();a=c.children().last();a.find("[data-onnew]").each(function(){seraph_pds.Gen.GetObjField(window,jQuery(this).data("onnew"))(this)});w(a)}},MoveItem:function(a,c,e){if(jQuery(a).find("ul.items-list").first().length){a=jQuery(c).closest("li.item").first();var b=0<e?a.next():0>e?a.prev():void 0;b&&b.length&&A(a,function(a,c){0<e?a.insertAfter(b):a.insertBefore(b);w(a,c)})}},DelItem:function(a,c){var b=jQuery(a),d=b.find("ul.items-list").first();d.length&&A(jQuery(c).closest("li.item").first(),
function(a,c){(c=d[0]._ItemsListCtx.onItemDel)&&c(b,d,a);a.remove();x(b,d)})},DelAllItems:function(a,c){var b=jQuery(a),d=b.find("ul.items-list").first();if(d.length){var f=d.children();f.addClass("smoothop");f.css("opacity",0);setTimeout(function(){f.each(function(){var a=jQuery(this),c=d[0]._ItemsListCtx.onItemDel;c&&c(b,d,a);a.remove()});x(b,d)},200)}}},_cb:{CheckBoxTree_OnChange:function(a){function b(a){var d=a.parent().parent(),e=!0;a.siblings().each(function(){return e=jQuery(this).children("label").find('input[type="checkbox"]').prop("checked")===
c});e&&c?(d.children("label").find('input[type="checkbox"]').prop({indeterminate:!1,checked:c}),b(d)):e&&!c?(d.children("label").find('input[type="checkbox"]').prop("checked",c),d.children("label").find('input[type="checkbox"]').prop("indeterminate",0<d.find('input[type="checkbox"]:checked').length),b(d)):a.parents("li").children("label").find('input[type="checkbox"]').prop({indeterminate:!0,checked:!1})}var c=jQuery(a).prop("checked");a=jQuery(a).parent().parent();a.find('input[type="checkbox"]').prop({indeterminate:!1,
checked:c});b(a)},ToggleButton_OnClick:function(a,c){function b(){f.find("[data-onexpand]").each(function(){seraph_pds.Gen.GetObjField(window,jQuery(this).data("onexpand"))(this,g)});f.toggle();d.find(".dashicons").removeClass(g?"dashicons-arrow-down":"dashicons-arrow-up").addClass(g?"dashicons-arrow-up":"dashicons-arrow-down")}var d=jQuery(c);c=jQuery(c.parentNode);var f=jQuery("#"+a),g="none"==f.css("display");a=f.data("onexpand");var k;a&&(k=seraph_pds.Gen.GetObjField(window,a)(f[0],g));if(k){var h=
c.find(".seraph_pds_spinner");d.attr("disabled","");h.show();k.finally(function(){b();h.hide();d.removeAttr("disabled")})}else b()},TokensList_DelItem:function(a){var b=jQuery(a.parentNode),c=b.data("id");a=jQuery(b[0].parentNode).find('input[type="hidden"]');b.remove();(b=seraph_pds.Gen.JsonParse(decodeURIComponent(a.val())))&&b.length&&(c=b.indexOf("string"==typeof b[0]?""+c:c),-1!=c&&(b.splice(c,1),a.val(encodeURIComponent(JSON.stringify(b)))))}}}})();
